# Generated by Django 2.2.6 on 2019-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chairman_Name', models.CharField(max_length=100)),
                ('Chairman_Username', models.EmailField(max_length=100, unique=True)),
                ('Chairman_Password', models.CharField(max_length=100, unique=True)),
                ('Chairman_Department', models.CharField(max_length=100, unique=True)),
                ('Department_Id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
